kinematic_plugins:
  inv_kin_plugins:
    positioner_only:
      plugins:
        KDLInvKinChainLMA:
          class: KDLInvKinChainLMAFactory
          config:
            base_link: positioner_base_link
            tip_link: positioner_tool0
    robot_only:
      plugins:
        OPWInvKin:
          class: OPWInvKinFactory
          config:
            base_link: base_link
            tip_link: tool0
            params:
              a1: 0.150
              a2: -0.115
              b: 0.00
              c1: 0.445
              c2: 0.7
              c3: 0.795
              c4: 0.085
              offsets: [0, 0, -1.57079632679, 0, 0, 0]
              sign_corrections: [1, 1, 1, 1, 1, 1]
    manipulator:
      plugins:
        REPInvKin:
          class: REPInvKinFactory
          config:
            manipulator_reach: 2.3
            positioner_sample_resolution:
              - name: positioner_base_joint
                value: 0.1
                min: -0.2
                max: 0.2
              - name: positioner_joint_1
                value: 0.1
                min: -0.2
                max: 0.2
            positioner:
              class: KDLFwdKinChainFactory
              config:
                base_link: positioner_base_link
                tip_link: positioner_tool0
            manipulator:
              class: OPWInvKinFactory
              config:
                base_link: base_link
                tip_link: tool0
                params:
                  a1: 0.150
                  a2: -0.115
                  b: 0.00
                  c1: 0.445
                  c2: 0.7
                  c3: 0.795
                  c4: 0.085
                  offsets: [0, 0, -1.57079632679, 0, 0, 0]
                  sign_corrections: [1, 1, 1, 1, 1, 1]
